name: Dispatch NPM Release

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: Module (node-infra|agent-infra|ra-core-infra|ra-infra|electron-infra)
        options:
          - node-infra
          - agent-infra
          - ra-core-infra
          - ra-infra
          - electron-infra

      build_mode:
        type: choice
        description: Build Mode (patch | minor | major | pre<patch | minor | major | release>)
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

env:
  MODULE: ${{ github.event.inputs.module }}
  BUILD_MODE: ${{ github.event.inputs.build_mode }}

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.0

      - name: Setup Git
        run: |
          git config user.name "mt-ci gh-action"
          git config user.email "mt-ci@gh-action.none"

      - name: Verify build_mode
        run: |
          echo "mt-ci | Module: $MODULE | Build mode: $BUILD_MODE"

      - name: Install dependencies
        run: |
          bun install

      - name: Linting application source
        run: |
          bun run --filter "./packages/$MODULE" lint

      - name: Building + Versioning application artifact
        run: |
          echo "Module: $MODULE | Build mode: $BUILD_MODE"

          echo "Cleaning up release folder"
          bun run --filter "./packages/$MODULE" clean

          echo "Compiling $MODULE"
          bun run --filter "./packages/$MODULE" rebuild:$BUILD_MODE

      - name: Push latest version to repository
        run: |
          cd packages/$MODULE

          PACKAGE_PATH="./package.json"
          VERSION=$(jq -r .version $PACKAGE_PATH)

          git fetch
          git checkout develop
          git add .
          git commit -m "Module: $MODULE | Build mode: $BUILD_MODE | Version: $VERSION | Release latest src"
          git push origin develop

          git checkout main
          git merge --allow-unrelated-histories develop
          git push origin main

      - name: Publish package on Registry ðŸ“¦
        run: |
          cd packages/$MODULE
          npm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
